NK\HintBundle\Entity\Matiere:
    type: entity
    table: null
    repositoryClass: NK\HintBundle\Repository\MatiereRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        intitule:
            type: string
            length: 255
    lifecycleCallbacks: {  }
