<?php

namespace NK\HintBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenirDocumentsPourUneMatiere($nomMatiere, $nomNiveau)
	{
		$qb = $this->createQueryBuilder('a')
				->Join('a.matiere', 'b', 'WITH', 'b.nomMatiere = :nomMatiere')
				->addSelect('b')
				->Join('b.niveau', 'c', 'WITH', 'c.nomNiveau = :nomNiveau')
				->addSelect('c')
				->setParameters(array('nomMatiere' => $nomMatiere, 'nomNiveau' => $nomNiveau));
		return $qb->getQuery()
				->getResult();
	}
}
