<?php

namespace NK\HintBundle\Repository;

/**
 * SousNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousNiveauRepository extends \Doctrine\ORM\EntityRepository
{
}
