nk_hint_subjectsPerLevel:
    path:     /{idCycle}/matieres/{idNiveau}/{idMatiere}
    defaults: { _controller: NKHintBundle:SubjectsLevels:subjects, idCycle: 0, idNiveau: 0, idMatiere: 0}

nk_hint_cours:
    path:     /cours
    defaults: { _controller: NKHintBundle:Document:cours }

nk_hint_exercices:
    path:     /exercices
    defaults: { _controller: NKHintBundle:Document:exercices }
