nk_hint_subjectsPerLevel:
    path:     /{niveauId}/matières/{matiereSelectionneeId}
    defaults: 
         _controller: NKHintBundle:SubjectsLevels:subjects 
         matiereSelectionneeId:    0

nk_hint_cours:
    path:     /cours
    defaults: { _controller: NKHintBundle:Document:cours }

nk_hint_exercices:
    path:     /exercices
    defaults: { _controller: NKHintBundle:Document:exercices }
