nk_hint_subjectsPerLevel:
    path:     /{idCycle}/matieres/{idNiveau}/{idMatiere}
    defaults: { _controller: NKHintBundle:SubjectsLevels:subjects, idCycle: 0, idNiveau: 0, idMatiere: 0}

nk_hint_coursexos:
    path:     /cours_exercices/{nomNiveau}/{nomMatiere}
    defaults: { _controller: NKHintBundle:Document:coursexos }

nk_hint_ajouterdoc:
    path:     /ajouter_document
    defaults: { _controller: NKHintBundle:Document:ajouterdoc }