nk_hint_subjectsPerLevel:
    path:     /{nomCycle}/matieres/{nomNiveau}/{idMatiere}
    defaults: { _controller: NKHintBundle:SubjectsLevels:subjects, nomCycle: '0', nomNiveau: '0', idMatiere: 0}

nk_hint_coursexos:
    path:     /cours_exercices/{nomNiveau}/{nomMatiere}
    defaults: { _controller: NKHintBundle:Document:coursexos }

nk_hint_ajouterdoc:
    path:     /ajouter_document
    defaults: { _controller: NKHintBundle:Document:ajouterdoc }

nk_hint_afficherdoc:
    path:     /afficher_document/{idDocument}
    defaults: { _controller: NKHintBundle:Document:afficherDocument }